Repository apache/dubbo, pull requests merged in 2018-09, with the labels that each got.

#2483 fix wording issue in dubbo-issue-report-template.md
  .github/ISSUE_TEMPLATE/dubbo-issue-report-template.md
Labels: status/READY-TO-MERGE

#2506 [Dubbo-2471] Fix invalid name issue in web-fragment.xml
  dubbo-config/dubbo-config-spring/src/main/resources/META-INF/web-fragment.xml
Labels: status/READY-TO-MERGE

#2325 [Dubbo-2323]the AsyncRpcResult should store the copy of the context #2323
  dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AsyncRpcResult.java
  dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcContext.java
Labels: status/need-triage

#2434 Remove method.async of provider url.
  dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/ClusterUtils.java
Labels: status/need-triage

#2409 [Dubbo-2348 ] AbstractRegistry util test enhancement
  dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/support/AbstractRegistryTest.java
Labels: status/READY-TO-MERGE

#2480 Support for caching null values
  dubbo-filter/dubbo-filter-cache/src/main/java/org/apache/dubbo/cache/filter/CacheFilter.java
  dubbo-filter/dubbo-filter-cache/src/test/java/org/apache/dubbo/cache/filter/CacheFilterTest.java
Labels: status/waiting-for-feedback

#2571 NullPointerException
  dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
Labels: status/READY-TO-MERGE
