Repository apache/dubbo, pull requests merged in 2018-08, with the labels that each got.

#2198 [Dubbo-655] Update Jetty to Version 9 #655
  dubbo-dependencies-bom/pom.xml
  dubbo-registry/dubbo-registry-api/pom.xml
  dubbo-remoting/dubbo-remoting-http/pom.xml
  dubbo-remoting/dubbo-remoting-http/src/main/java/org/apache/dubbo/remoting/http/jetty/JettyHttpServer.java
  dubbo-rpc/dubbo-rpc-dubbo/pom.xml
  pom.xml
Labels: status/READY-TO-MERGE

#2213 [Dubbo-2187] Use CompletetableFuture to rewrite the embedded ListenableFuture
  dubbo-common/src/main/java/org/apache/dubbo/common/concurrent/ListenableFuture.java
  dubbo-common/src/main/java/org/apache/dubbo/common/concurrent/ListenableFutureTask.java
  dubbo-common/src/test/java/org/apache/dubbo/common/concurrent/CompletableFutureTaskTest.java
  dubbo-monitor/dubbo-monitor-api/src/main/java/org/apache/dubbo/monitor/support/AbstractMonitorFactory.java
  dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/zkclient/ZkClientWrapper.java
Labels: status/waiting-for-feedback

#2183 [Dubbo-#2162]Correct the reference retries default value 0 to 2
  dubbo-compatible/src/main/java/com/alibaba/dubbo/config/annotation/Reference.java
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/annotation/Reference.java
  dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/annotation/AnnotationPropertyValuesAdapterTest.java
Labels: status/waiting-for-feedback

#2279 add log4j2 extension
  dubbo-common/pom.xml
  dubbo-common/src/main/java/org/apache/dubbo/common/logger/LoggerFactory.java
  dubbo-common/src/main/java/org/apache/dubbo/common/logger/log4j2/Log4j2Logger.java
  dubbo-common/src/main/java/org/apache/dubbo/common/logger/log4j2/Log4j2LoggerAdapter.java
  dubbo-common/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.common.logger.LoggerAdapter
  dubbo-common/src/test/java/org/apache/dubbo/common/logger/LoggerAdapterTest.java
  dubbo-common/src/test/java/org/apache/dubbo/common/logger/slf4j/Slf4jLoggerTest.java
  dubbo-dependencies-bom/pom.xml
Labels: status/need-triage

#2103 replace the method httpclient which is annotated with “@Deprecated”
  dubbo-rpc/dubbo-rpc-hessian/src/main/java/org/apache/dubbo/rpc/protocol/hessian/HessianProtocol.java
  dubbo-rpc/dubbo-rpc-hessian/src/main/java/org/apache/dubbo/rpc/protocol/hessian/HttpClientConnectionFactory.java
Labels: status/READY-TO-MERGE

#2228 [Dubbo- support tag router feature] Add a new Router implement -- TagRouter
  dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/tag/TagRouter.java
  dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/tag/TagRouterFactory.java
  dubbo-cluster/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.rpc.cluster.RouterFactory
  dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/router/tag/TagRouterTest.java
  dubbo-common/src/main/java/org/apache/dubbo/common/Constants.java
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractReferenceConfig.java
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractServiceConfig.java
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/annotation/Service.java
  dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/AnnotationBean.java
  dubbo-config/dubbo-config-spring/src/main/resources/META-INF/compat/dubbo.xsd
  dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd
  dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java
Labels: status/waiting-for-feedback

#2185 Direct return when the server goes down unnormally.
  dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/Channel.java
  dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/ExchangeChannel.java
  dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/Response.java
  dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/DefaultFuture.java
  dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeHandler.java
  dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/AbstractChannel.java
  dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/DubboInvokerAvilableTest.java
  dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/MultiThreadTest.java
  dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/ReferenceCountExchangeClientTest.java
  dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/RpcFilterTest.java
  dubbo-rpc/dubbo-rpc-thrift/src/test/java/org/apache/dubbo/rpc/protocol/thrift/ThriftCodecTest.java
Labels: status/waiting-for-feedback

#2360 [Dubbo-issue1814][ Baiji-9] Add .xml configuration of graceful close
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ApplicationConfig.java
  dubbo-config/dubbo-config-spring/src/main/resources/META-INF/compat/dubbo.xsd
Labels: status/READY-TO-MERGE
