Repository apache/dubbo, pull requests merged in 2018-04, with the labels that each got.

#1607 [Dubbo-shutdown gracefully] fix shutdown gracefully.
  dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/ProtocolConfig.java
  dubbo-config/dubbo-config-spring/src/main/java/com/alibaba/dubbo/config/spring/AnnotationBean.java
  dubbo-remoting/dubbo-remoting-api/src/main/java/com/alibaba/dubbo/remoting/exchange/support/header/HeaderExchangeServer.java
  dubbo-rpc/dubbo-rpc-dubbo/src/test/java/com/alibaba/dubbo/rpc/protocol/dubbo/DubboInvokerAvilableTest.java
Labels: type/bug

#1620 [Dubbo-1619] Fix exception stack trace during provider demo start.
  dubbo-common/src/main/java/com/alibaba/dubbo/common/Constants.java
  dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/ServiceConfig.java
Labels: level/easy, priority/low, type/enhancement

#1444 [Dubbo-RpcContext] Simplify check consumer side in RpcContext
  dubbo-rpc/dubbo-rpc-api/src/main/java/com/alibaba/dubbo/rpc/RpcContext.java
Labels: status/READY-TO-MERGE, type/refactor

#1449 fixes #1089, make ExecutionDispatcher meet dubbo-user-book
  dubbo-remoting/dubbo-remoting-api/src/main/java/com/alibaba/dubbo/remoting/transport/dispatcher/execution/ExecutionChannelHandler.java
Labels: level/easy, priority/low, status/READY-TO-MERGE, type/enhancement
