Repository apache/dubbo, pull requests merged in 2018-02, with the labels that each got.

#1353 fix oninvoke inject failed
  dubbo-config/dubbo-config-spring/src/main/java/com/alibaba/dubbo/config/spring/schema/DubboBeanDefinitionParser.java
Labels: status/waiting-for-feedback

#1378 Simplify string concatenation in log
  dubbo-remoting/dubbo-remoting-api/src/main/java/com/alibaba/dubbo/remoting/transport/DecodeHandler.java
Labels: status/READY-TO-MERGE

#1331 add optional parameter to support hessian protocol method overload and request protocol version
  dubbo-common/src/main/java/com/alibaba/dubbo/common/Constants.java
  dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd
  dubbo-rpc/dubbo-rpc-hessian/src/main/java/com/alibaba/dubbo/rpc/protocol/hessian/HessianProtocol.java
  dubbo-rpc/dubbo-rpc-hessian/src/test/java/com/alibaba/dubbo/rpc/protocol/hessian/HessianProtocolTest.java
  dubbo-rpc/dubbo-rpc-hessian/src/test/java/com/alibaba/dubbo/rpc/protocol/hessian/HessianService.java
  dubbo-rpc/dubbo-rpc-hessian/src/test/java/com/alibaba/dubbo/rpc/protocol/hessian/HessianServiceImpl.java
Labels: status/waiting-for-feedback

#1376 Do not instantiate load balance if there is no invokers (#1297)
  dubbo-cluster/src/main/java/com/alibaba/dubbo/rpc/cluster/support/AbstractClusterInvoker.java
Labels: status/waiting-for-feedback

#1040 Refactor, replace some deprecated methods related with jedis and UT
  dubbo-registry/dubbo-registry-redis/src/main/java/com/alibaba/dubbo/registry/redis/RedisRegistry.java
Labels: priority/low, status/waiting-for-feedback, type/refactor
