Repository apache/dubbo, pull requests merged in 2019-10, with the labels that each got.

#5137 Adjust remoting-grizzly test sources root
  dubbo-remoting/dubbo-remoting-grizzly/src/test/java/org/apache/dubbo/remoting/transport/grizzly/GrizzlyTransporterTest.java
Labels: first-time-contributor

#5143 Add license for licenseCheck.sh
  licenseCheck.sh
Labels: first-time-contributor

#5149 remove sensitive data from the timeout log
  dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/DefaultFuture.java
Labels: status/need-triage

#5158 [Dubbo-4871] fix cache file name issue in windows platform
  dubbo-metadata-report/dubbo-metadata-report-api/src/main/java/org/apache/dubbo/metadata/support/AbstractMetadataReport.java
  dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java
Labels: first-time-contributor, type/bug

#5177 fix GenericServiceTest failing on Travis to master
  dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/service/GenericServiceTest.java
  dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/validation/ValidationTest.java
Labels: first-time-contributor, status/READY-TO-MERGE
