Repository apache/dubbo, pull requests merged in 2019-09, with the labels that each got.

#4980 Simplify some code where feasible
  dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/configurator/parser/ConfigParser.java
  dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/RoundRobinLoadBalance.java
  dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/ForkingClusterInvoker.java
  dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/RoundRobinLoadBalanceTest.java
  dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/FailoverClusterInvokerTest.java
  dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/MergeableClusterInvokerTest.java
Labels: first-time-contributor

#4935 considering methodStatus.active == Integer.MAX_VALUE
  dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcStatus.java
Labels: first-time-contributor

#4948 add Apollo config center mock test
  dubbo-configcenter/dubbo-configcenter-apollo/pom.xml
  dubbo-configcenter/dubbo-configcenter-apollo/src/test/java/org/apache/dubbo/configcenter/support/apollo/ApolloDynamicConfigurationTest.java
  dubbo-configcenter/dubbo-configcenter-apollo/src/test/resources/META-INF/app.properties
  dubbo-configcenter/dubbo-configcenter-apollo/src/test/resources/mockdata-dubbo.properties
Labels: status/waiting-for-feedback, type/unit-test

#4974 nacos-registry:serviceName split error
  dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java
  dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosServiceName.java
Labels: first-time-contributor

#4076 optimize generic invoke
  dubbo-dependencies-bom/pom.xml
  dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/Constants.java
  dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/GenericFilter.java
  dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/support/ProtocolUtils.java
Labels: type/enhancement

#5009 avoid resize
  dubbo-common/src/main/java/org/apache/dubbo/common/utils/ClassUtils.java
Labels: first-time-contributor

#4955 fix default setting
  dubbo-config/dubbo-config-spring/src/main/java/com/alibaba/dubbo/config/spring/beans/factory/annotation/AnnotationInjectedBeanPostProcessor.java
  dubbo-config/dubbo-config-spring/src/main/java/com/alibaba/dubbo/config/spring/beans/factory/annotation/DubboConfigBindingBeanPostProcessor.java
Labels: first-time-contributor, status/feedback-provided

#5044 fix some typos
  dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/LeastActiveLoadBalance.java
Labels: first-time-contributor

#5042 fix doc typo in CacheFilter.java
  dubbo-filter/dubbo-filter-cache/src/main/java/org/apache/dubbo/cache/filter/CacheFilter.java
Labels: first-time-contributor, type/documentation

#5070 [Dubbo-4331] Improve api doc #4331
  pom.xml
Labels: first-time-contributor, type/documentation

#5063 [Dubbo-5049]support @Bean on Config class to config id as alias
  dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/DubboConfigBindingBeanPostProcessor.java
  dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/annotation/DubboConfigBindingBeanPostProcessorTest.java
Labels: first-time-contributor, status/need-triage

#5102 修复 CollectionUtils类toStringMap方法没有检查 pairs 参数是否为空.
  dubbo-common/src/main/java/org/apache/dubbo/common/utils/CollectionUtils.java
Labels: first-time-contributor

#5099 Fixes a bug in gson's deserialization feature
  dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DecodeableRpcResult.java
  dubbo-serialization/dubbo-serialization-gson/src/main/java/org/apache/dubbo/common/serialize/gson/GsonJsonObjectInput.java
Labels: first-time-contributor

#5112 refactor some string operations with StringUtils
  dubbo-common/src/main/java/org/apache/dubbo/common/URL.java
  dubbo-common/src/main/java/org/apache/dubbo/common/URLBuilder.java
  dubbo-common/src/main/java/org/apache/dubbo/common/Version.java
Labels: first-time-contributor
