Repository apache/dubbo, pull requests merged in 2019-05, with the labels that each got.

#3970 optimize constant naming style
  dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/merger/MergerFactory.java
  dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/Proxy.java
  dubbo-common/src/main/java/org/apache/dubbo/common/threadlocal/InternalThreadLocal.java
  dubbo-common/src/main/java/org/apache/dubbo/common/threadlocal/InternalThreadLocalMap.java
  dubbo-common/src/main/java/org/apache/dubbo/common/utils/AtomicPositiveInteger.java
  dubbo-common/src/main/java/org/apache/dubbo/common/utils/ExecutorUtil.java
  dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractConfig.java
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/DubboShutdownHook.java
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/context/ConfigManager.java
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ReferenceConfigCache.java
  dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/utils/ReferenceConfigCacheTest.java
  dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/extension/SpringExtensionFactory.java
  dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java
  dubbo-remoting/dubbo-remoting-http/src/main/java/org/apache/dubbo/remoting/http/servlet/ServletManager.java
  dubbo-remoting/dubbo-remoting-mina/src/main/java/org/apache/dubbo/remoting/transport/mina/MinaClient.java
  dubbo-remoting/dubbo-remoting-netty/src/main/java/org/apache/dubbo/remoting/transport/netty/NettyChannel.java
  dubbo-remoting/dubbo-remoting-netty/src/main/java/org/apache/dubbo/remoting/transport/netty/NettyClient.java
  dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyChannel.java
  dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/curator/CuratorZookeeperClient.java
  dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/AccessLogFilter.java
  dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/model/ApplicationModel.java
  dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/CallbackServiceCodec.java
  dubbo-rpc/dubbo-rpc-http/src/main/java/org/apache/dubbo/rpc/protocol/http/HttpRemoteInvocation.java
  dubbo-rpc/dubbo-rpc-thrift/src/main/java/org/apache/dubbo/rpc/protocol/thrift/ThriftCodec.java
  dubbo-rpc/dubbo-rpc-thrift/src/main/java/org/apache/dubbo/rpc/protocol/thrift/ThriftType.java
  dubbo-rpc/dubbo-rpc-thrift/src/test/java/org/apache/dubbo/rpc/protocol/thrift/ThriftCodecTest.java
  dubbo-serialization/dubbo-serialization-api/src/main/java/org/apache/dubbo/common/serialize/support/SerializableClassRegistry.java
Labels: first-time-contributor

#3953 improve NetUtils
  dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java
  dubbo-common/src/test/java/org/apache/dubbo/common/utils/NetUtilsTest.java
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ApplicationConfig.java
  dubbo-demo/dubbo-demo-api/dubbo-demo-api-provider/src/main/java/org/apache/dubbo/demo/provider/Application.java
Labels: status/waiting-for-feedback

#3975 [Dubbo-3829] support google pb generic invocation
  dubbo-all/pom.xml
  dubbo-bom/pom.xml
  dubbo-common/src/main/java/org/apache/dubbo/common/Constants.java
  dubbo-dependencies-bom/pom.xml
  dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/GenericFilter.java
  dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/support/ProtocolUtils.java
  dubbo-serialization/dubbo-serialization-protobuf-json/pom.xml
  dubbo-serialization/dubbo-serialization-protobuf-json/src/main/java/org/apache/dubbo/common/serialize/protobuf/support/GenericProtobufObjectInput.java
  dubbo-serialization/dubbo-serialization-protobuf-json/src/main/java/org/apache/dubbo/common/serialize/protobuf/support/GenericProtobufObjectOutput.java
  dubbo-serialization/dubbo-serialization-protobuf-json/src/main/java/org/apache/dubbo/common/serialize/protobuf/support/GenericProtobufSerialization.java
  dubbo-serialization/dubbo-serialization-protobuf-json/src/main/java/org/apache/dubbo/common/serialize/protobuf/support/ProtobufUtils.java
  dubbo-serialization/dubbo-serialization-protobuf-json/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.common.serialize.Serialization
  dubbo-serialization/dubbo-serialization-test/pom.xml
  dubbo-serialization/dubbo-serialization-test/src/test/java/org/apache/dubbo/common/serialize/protobuf/support/GenericProtobufObjectOutputTest.java
  dubbo-serialization/dubbo-serialization-test/src/test/java/org/apache/dubbo/common/serialize/protobuf/support/GenericProtobufSerializationTest.java
  dubbo-serialization/dubbo-serialization-test/src/test/java/org/apache/dubbo/common/serialize/protobuf/support/model/GooglePB.java
  dubbo-serialization/dubbo-serialization-test/src/test/resources/protobuf/GooglePB.proto
  dubbo-serialization/pom.xml
Labels: first-time-contributor

#4006 optimize some code style
  dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java
  dubbo-metadata-report/dubbo-metadata-report-api/src/main/java/org/apache/dubbo/metadata/support/AbstractMetadataReport.java
  dubbo-monitor/dubbo-monitor-default/src/main/java/org/apache/dubbo/monitor/dubbo/MetricsFilter.java
  dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/impl/Ls.java
  dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java
  dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistryFactory.java
  dubbo-remoting/dubbo-remoting-etcd3/src/main/java/org/apache/dubbo/remoting/etcd/jetcd/JEtcdClientWrapper.java
  dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ActiveLimitFilter.java
  dubbo-serialization/dubbo-serialization-gson/src/main/java/org/apache/dubbo/common/serialize/gson/GsonJsonObjectInput.java
Labels: status/READY-TO-MERGE

#4026 fix telnet not work in some scene (#4007)
  dubbo-common/src/main/java/org/apache/dubbo/common/utils/PojoUtils.java
  dubbo-common/src/test/java/org/apache/dubbo/common/model/User.java
  dubbo-common/src/test/java/org/apache/dubbo/common/utils/PojoUtilsTest.java
Labels: first-time-contributor

#4056 change concurrent list to regular list
  dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocol.java
Labels: first-time-contributor, status/READY-TO-MERGE

#3685 [Dubbo-3669]do local export before register any listener.
  dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/AbstractConfiguratorListener.java
Labels: status/READY-TO-MERGE

#4067 ReferenceConfig initialized not changed to false once subscribe throws exception
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
Labels: first-time-contributor

#4100 update erlang link
  README.md
Labels: first-time-contributor

#4110 rm incubating word
  README.md
Labels: status/READY-TO-MERGE

#3863 [#3817]Support Redis cluster in Metadata Report
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/MetadataReportConfig.java
  dubbo-config/dubbo-config-spring/src/main/resources/META-INF/compat/dubbo.xsd
  dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd
  dubbo-metadata-report/dubbo-metadata-report-api/src/main/java/org/apache/dubbo/metadata/identifier/MetadataIdentifier.java
  dubbo-metadata-report/dubbo-metadata-report-redis/src/main/java/org/apache/dubbo/metadata/store/redis/RedisMetadataReport.java
Labels: status/waiting-for-feedback

#4157 [CI] Add enforce maven plugin to do snapshot version check
  pom.xml
Labels: status/READY-TO-MERGE

#4186 Remove licence from dependency
  dubbo-dependencies-bom/pom.xml
Labels: status/READY-TO-MERGE

#4162 reverse url of python
  README.md
Labels: status/DO-NOT-MERGE
