Repository apache/dubbo, pull requests merged in 2019-11, with the labels that each got.

#5238 [DUBBO-5237] fix NetUtils#isPreferIPV6Address() always return false
  dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java
Labels: first-time-contributor

#5265 Clean up CommandHelper class and add its private ctor
  dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/util/CommandHelper.java
Labels: first-time-contributor

#5043 concurrent cache bug fix
  dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/Wrapper.java
Labels: status/need-triage

#5144 fix NacosRegistry weight missing issue
  dubbo-registry/dubbo-registry-nacos/src/main/java/com/alibaba/dubbo/registry/nacos/NacosRegistry.java
  dubbo-registry/dubbo-registry-nacos/src/main/java/com/alibaba/dubbo/registry/nacos/NacosRegistryFactory.java
Labels: status/waiting-for-feedback, type/bug

#5201 [Dubbo-5200] fix javadoc for Serialization.getContentTypeId
  dubbo-serialization/dubbo-serialization-api/src/main/java/org/apache/dubbo/common/serialize/Serialization.java
Labels: status/waiting-for-feedback, type/documentation

#5395 [ISSURE] update alibaba_spring_context_support_version to 1.0.5
  dubbo-dependencies-bom/pom.xml
Labels: first-time-contributor
