Repository apache/dubbo, pull requests merged in 2019-04, with the labels that each got.

#3803 [Dubbo-3795] replace hard code strings with constants in config moudule
  dubbo-common/src/main/java/org/apache/dubbo/common/Constants.java
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ProviderConfig.java
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/RegistryConfig.java
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
Labels: first-time-contributor

#3820 polish code
  dubbo-registry/dubbo-registry-nacos/pom.xml
  dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperRegistry.java
Labels: type/enhancement

#3786 Add JSON-RPC protocol
  dubbo-all/pom.xml
  dubbo-bom/pom.xml
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ApplicationConfig.java
  dubbo-dependencies-bom/pom.xml
  dubbo-distribution/pom.xml
  dubbo-rpc/dubbo-rpc-jsonrpc/pom.xml
  dubbo-rpc/dubbo-rpc-jsonrpc/src/main/java/org/apache/dubbo/rpc/protocol/jsonrpc/JsonRpcProtocol.java
  dubbo-rpc/dubbo-rpc-jsonrpc/src/main/resources/META-INF/dubbo/internal/com.alibaba.dubbo.rpc.Protocol
  dubbo-rpc/dubbo-rpc-jsonrpc/src/test/java/org/apache/dubbo/rpc/protocol/jsonrpc/JsonRpcProtocolTest.java
  dubbo-rpc/dubbo-rpc-jsonrpc/src/test/java/org/apache/dubbo/rpc/protocol/jsonrpc/JsonRpcService.java
  dubbo-rpc/dubbo-rpc-jsonrpc/src/test/java/org/apache/dubbo/rpc/protocol/jsonrpc/JsonRpcServiceImpl.java
  dubbo-rpc/pom.xml
  dubbo-test/pom.xml
Labels: status/waiting-for-feedback

#3833 metrics service
  dubbo-common/src/main/java/org/apache/dubbo/common/Constants.java
  dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/MetricsConfig.java
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
  dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ReferenceBean.java
  dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ServiceBean.java
  dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/schema/DubboNamespaceHandler.java
  dubbo-config/dubbo-config-spring/src/main/resources/META-INF/compat/dubbo.xsd
  dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd
  dubbo-monitor/dubbo-monitor-api/pom.xml
  dubbo-monitor/dubbo-monitor-api/src/main/java/org/apache/dubbo/monitor/MetricsService.java
  dubbo-monitor/dubbo-monitor-api/src/main/java/org/apache/dubbo/monitor/support/MetricsFilter.java
  dubbo-monitor/dubbo-monitor-api/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.rpc.Filter
  dubbo-monitor/dubbo-monitor-api/src/test/java/org/apache/dubbo/monitor/support/MetricsFilterTest.java
  dubbo-monitor/dubbo-monitor-default/pom.xml
  dubbo-monitor/dubbo-monitor-default/src/main/java/org/apache/dubbo/monitor/dubbo/MetricsFilter.java
  dubbo-monitor/dubbo-monitor-default/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.rpc.Filter
  dubbo-monitor/dubbo-monitor-default/src/test/java/org/apache/dubbo/monitor/dubbo/MetricsFilterTest.java
  dubbo-monitor/dubbo-monitor-default/src/test/java/org/apache/dubbo/monitor/dubbo/service/DemoService.java
Labels: first-time-contributor

#3867 Fix javadoc for Adaptive.value()
  dubbo-common/src/main/java/org/apache/dubbo/common/extension/Adaptive.java
Labels: status/READY-TO-MERGE

#3869 make protocols a mutable list (a concrete ArrayList)
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractServiceConfig.java
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ProviderConfig.java
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
  dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/AbstractServiceConfigTest.java
  dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/url/UrlTestBase.java
Labels: first-time-contributor, status/READY-TO-MERGE

#3900 update comment for "dynamic" field
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractServiceConfig.java
Labels: first-time-contributor

#3898 Add Erlang Implementation
  README.md
Labels: first-time-contributor

#3624 add socks5 proxy support
  dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyClient.java
Labels: first-time-contributor, type/question & discussion, type/requirement

#3888 [Dubbo-3826] Auth support for redis metadata report
  dubbo-metadata-report/dubbo-metadata-report-redis/src/main/java/org/apache/dubbo/metadata/store/redis/RedisMetadataReport.java
  dubbo-metadata-report/dubbo-metadata-report-redis/src/test/java/org/apache/dubbo/metadata/store/redis/RedisMetadataReportTest.java
Labels: first-time-contributor

#3940 There's no need to null test in conjunction with an instanceof test. …
  dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/DecodeHandler.java
Labels: first-time-contributor, status/READY-TO-MERGE

#3959 [DUBBO-3952]: Dubbo 2.7.1 ： delay export function doesn't work,
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
Labels: status/READY-TO-MERGE
