Repository apache/dubbo, pull requests merged in 2019-12, with the labels that each got.

#5403 improve InvokerInvocationHandler#invoke
  dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/proxy/InvokerInvocationHandler.java
Labels: type/refactor

#5366 [Dubbo-5365] Fix Apollo config center not work via XML configuration
  dubbo-configcenter/dubbo-configcenter-apollo/src/main/java/org/apache/dubbo/configcenter/support/apollo/ApolloDynamicConfiguration.java
Labels: first-time-contributor

#5337 add the router key in dubbo.xsd
  dubbo-common/src/main/java/org/apache/dubbo/config/AbstractReferenceConfig.java
  dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/AbstractReferenceConfigTest.java
  dubbo-config/dubbo-config-spring/src/main/resources/META-INF/compat/dubbo.xsd
  dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd
Labels: status/waiting-for-feedback

#5430 [Dubbo-Optimize] Simple performance optimization
  dubbo-common/src/main/java/org/apache/dubbo/common/URL.java
  dubbo-common/src/main/java/org/apache/dubbo/common/utils/StringUtils.java
  dubbo-common/src/main/java/org/apache/dubbo/common/utils/UrlUtils.java
  dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ServiceDescriptor.java
  dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ServiceRepository.java
  dubbo-common/src/test/java/org/apache/dubbo/common/utils/StringUtilsTest.java
  dubbo-common/src/test/java/org/apache/dubbo/common/utils/UrlUtilsTest.java
  dubbo-monitor/dubbo-monitor-default/src/main/java/org/apache/dubbo/monitor/dubbo/DubboMonitor.java
  dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/support/RpcUtilsTest.java
  dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DecodeableRpcResult.java
Labels: status/READY-TO-MERGE

#5390 [Dubbo-5389] fix null attachment issue when consumer use generic
  dubbo-rpc/dubbo-rpc-api/src/main/java/com/alibaba/dubbo/rpc/filter/GenericFilter.java
Labels: first-time-contributor

#5380 Simplify the code and fix potential concurrent bug
  dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/RoundRobinLoadBalance.java
  dubbo-common/src/main/java/org/apache/dubbo/common/store/support/SimpleDataStore.java
  dubbo-common/src/main/java/org/apache/dubbo/common/utils/PojoUtils.java
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ReferenceConfigCache.java
  dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/AbstractRegistryService.java
  dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/SimpleRegistryService.java
  dubbo-monitor/dubbo-monitor-api/src/main/java/org/apache/dubbo/monitor/support/MonitorFilter.java
  dubbo-monitor/dubbo-monitor-default/src/main/java/org/apache/dubbo/monitor/dubbo/DubboMonitor.java
  dubbo-registry/dubbo-registry-default/src/test/java/org/apache/dubbo/registry/dubbo/AbstractRegistryService.java
  dubbo-registry/dubbo-registry-default/src/test/java/org/apache/dubbo/registry/dubbo/SimpleRegistryService.java
  dubbo-registry/dubbo-registry-multicast/src/main/java/org/apache/dubbo/registry/multicast/MulticastRegistry.java
  dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperRegistry.java
  dubbo-remoting/dubbo-remoting-etcd3/src/main/java/org/apache/dubbo/remoting/etcd/support/AbstractEtcdClient.java
  dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/support/AbstractZookeeperClient.java
  dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcStatus.java
  dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/filter/TraceFilter.java
Labels: first-time-contributor, type/refactor

#5270 fix AccessLogFilter TODO
  dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/AccessLogFilter.java
Labels: first-time-contributor, status/READY-TO-MERGE

#5352 optimize : use constants as callers to the equals() method
  dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/AbstractLoadBalance.java
  dubbo-common/src/main/java/org/apache/dubbo/common/constants/RegistryConstants.java
Labels: first-time-contributor

#5508 Use ReflectUtils#isPrimitives instead of JValidator#isPrimitives
  dubbo-filter/dubbo-filter-validation/src/main/java/org/apache/dubbo/validation/support/jvalidation/JValidator.java
Labels: type/refactor

#5506 [Dubbo] Refactoring to remove duplicate methods and feature envy.
  dubbo-common/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java
  dubbo-common/src/main/java/org/apache/dubbo/config/ReferenceConfigBase.java
  dubbo-common/src/main/java/org/apache/dubbo/config/ServiceConfigBase.java
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
Labels: first-time-contributor, type/refactor

#5533 Fix typo: paramter
  dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
  dubbo-common/src/main/java/org/apache/dubbo/config/RegistryConfig.java
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/builders/RegistryBuilder.java
Labels: type/refactor

#5548 [Dubbo-5537] remove unused variable in EtcdServiceDiscovery
  dubbo-registry/dubbo-registry-etcd3/src/main/java/org/apache/dubbo/registry/etcd/EtcdServiceDiscovery.java
Labels: first-time-contributor

#5556 [Dubbo-5554] Code Refactoring for Container contents that are never accessed #5554
  dubbo-common/src/main/java/org/apache/dubbo/common/compiler/support/JdkCompiler.java
  dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocol.java
Labels: first-time-contributor
