Repository apache/dubbo, pull requests merged in 2020-02, with the labels that each got.

#5585 optimize : put single-quotes around ':' to use the faster "indexOf(char)" method.
  dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/configurator/parser/ConfigParser.java
Labels: type/refactor

#5356 optimize : constant names should be all uppercase, separated by underscores
  dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/script/ScriptRouter.java
  dubbo-common/src/main/java/org/apache/dubbo/common/config/configcenter/file/FileSystemDynamicConfiguration.java
  dubbo-common/src/main/java/org/apache/dubbo/common/json/GenericJSONConverter.java
  dubbo-common/src/main/java/org/apache/dubbo/common/utils/ReflectUtils.java
  dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ApplicationModel.java
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
  dubbo-container/dubbo-container-api/src/main/java/org/apache/dubbo/container/Main.java
  dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/report/support/AbstractMetadataReport.java
  dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/store/BaseWritableMetadataService.java
  dubbo-metadata/dubbo-metadata-definition-protobuf/src/main/java/org/apache/dubbo/metadata/definition/protobuf/ProtobufTypeBuilder.java
  dubbo-monitor/dubbo-monitor-api/src/main/java/org/apache/dubbo/monitor/support/AbstractMonitorFactory.java
  dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/server/DubboLogo.java
  dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/server/Server.java
  dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/server/handler/QosProcessHandler.java
  dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/server/handler/TelnetProcessHandler.java
  dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/server/handler/TelnetProcessHandlerTest.java
  dubbo-remoting/dubbo-remoting-http/src/main/java/org/apache/dubbo/remoting/http/servlet/DispatcherServlet.java
  dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyClient.java
  dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/DeprecatedFilter.java
  dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/CallbackServiceCodec.java
  dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/filter/TraceFilter.java
  dubbo-rpc/dubbo-rpc-native-thrift/src/main/java/org/apache/dubbo/rpc/protocol/nativethrift/ThriftProtocol.java
  dubbo-serialization/dubbo-serialization-fst/src/main/java/org/apache/dubbo/common/serialize/fst/FstFactory.java
Labels: status/READY-TO-MERGE, type/refactor

#5580 [Dubbo-5560] fix useless null check in ServiceConfig
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
Labels: type/refactor

#5481 [Dubbo-5479] refactor generic invoke support
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ReferenceConfigCache.java
  dubbo-demo/dubbo-demo-api/dubbo-demo-api-consumer/src/main/java/org/apache/dubbo/demo/consumer/Application.java
  dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/Constants.java
  dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/GenericImplFilter.java
  dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/proxy/AbstractProxyFactory.java
Labels: type/enhancement

#5525 [Dubbo-perf]: Reduce object allocation for ProtocolUtils.serviceKey(int, Stri…
  dubbo-common/src/main/java/org/apache/dubbo/rpc/support/GroupServiceKeyCache.java
  dubbo-common/src/main/java/org/apache/dubbo/rpc/support/ProtocolUtils.java
  dubbo-common/src/test/java/org/apache/dubbo/rpc/support/ProtocolUtilsTest.java
Labels: type/performance

#5454 [Dubbo-5446] fix aop issue with @Reference
  dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceAnnotationBeanPostProcessor.java
Labels: status/need-triage

#5566 [Dubbo-3001] enhance the java doc of dubbo-rpc module.
  dubbo-rpc/dubbo-rpc-rmi/src/main/java/com/alibaba/dubbo/rpc/protocol/rmi/RmiRemoteInvocation.java
Labels: status/need-triage, type/documentation

#5559 [Dubbo] Refactoring to remove feature envy
  dubbo-common/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java
Labels: type/refactor

#5749 fix: spelling incorrect
  SECURITY.md
  dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/wrapper/MockClusterInvoker.java
  dubbo-common/src/main/java/org/apache/dubbo/common/json/JSON.java
  dubbo-common/src/main/java/org/apache/dubbo/config/MetadataReportConfig.java
  dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ServiceDescriptor.java
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/builders/MetadataReportBuilder.java
  dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/schema/DubboBeanDefinitionParser.java
  dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/util/DubboBeanUtils.java
  dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/store/RemoteWritableMetadataService.java
  dubbo-plugin/dubbo-auth/src/main/java/org/apache/dubbo/auth/AccessKeyAuthenticator.java
  dubbo-plugin/dubbo-auth/src/main/java/org/apache/dubbo/auth/Constants.java
  dubbo-plugin/dubbo-auth/src/main/java/org/apache/dubbo/auth/DefaultAccessKeyStorage.java
  dubbo-plugin/dubbo-auth/src/test/java/org/apache/dubbo/auth/AccessKeyAuthenticatorTest.java
  dubbo-plugin/dubbo-auth/src/test/java/org/apache/dubbo/auth/filter/ProviderAuthFilterTest.java
  dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/EventPublishingServiceDiscovery.java
  dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/SubscribedURLsSynthesizer.java
  dubbo-remoting/dubbo-remoting-etcd3/src/main/java/org/apache/dubbo/remoting/etcd/EtcdClient.java
  dubbo-remoting/dubbo-remoting-etcd3/src/main/java/org/apache/dubbo/remoting/etcd/jetcd/JEtcdClientWrapper.java
  dubbo-remoting/dubbo-remoting-mina/src/main/java/org/apache/dubbo/remoting/transport/mina/MinaClient.java
  dubbo-rpc/dubbo-rpc-native-thrift/src/test/idls/DemoService.thrift
Labels: status/READY-TO-MERGE, type/refactor
