Repository apache/dubbo, pull requests merged in 2020-12, with the labels that each got.

#6949 Fix samples urls in README
  README.md
Labels: type/documentation

#7028 Update CompatibleTypeUtils.java
  dubbo-common/src/main/java/org/apache/dubbo/common/utils/CompatibleTypeUtils.java
Labels: type/bug

#6836 fix host parse issue with ipv6 format
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ConfigValidationUtils.java
Labels: type/enhancement
