Repository apache/dubbo, pull requests merged in 2020-01, with the labels that each got.

#5565 [Dubbo-5468] fix duplicate code in CacheableRouterFactory
  dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/CacheableRouterFactory.java
Labels: first-time-contributor, type/refactor

#5558 Use stringUtils make code clean
  dubbo-common/src/main/java/org/apache/dubbo/rpc/support/ProtocolUtils.java
Labels: type/refactor

#5562 optimize : fix generic specification tips
  dubbo-serialization/dubbo-serialization-api/src/main/java/org/apache/dubbo/common/serialize/support/SerializableClassRegistry.java
  dubbo-serialization/dubbo-serialization-api/src/main/java/org/apache/dubbo/common/serialize/support/SerializationOptimizer.java
  dubbo-serialization/dubbo-serialization-test/src/test/java/org/apache/dubbo/common/serialize/support/SerializableClassRegistryTest.java
Labels: type/refactor

#5582 add sources profile
  pom.xml
Labels: status/waiting-for-feedback

#5586 optimize : optimize IOUtils.java "try" to "try resource"
  dubbo-common/src/main/java/org/apache/dubbo/common/utils/IOUtils.java
Labels: type/refactor

#5584 optimize : modify collection judgment method
  dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/configurator/parser/ConfigParser.java
Labels: status/READY-TO-MERGE

#5598 fix reuse ID
  dubbo-serialization/dubbo-serialization-api/src/main/java/org/apache/dubbo/common/serialize/Constants.java
  dubbo-serialization/dubbo-serialization-kryo/src/main/java/org/apache/dubbo/common/serialize/kryo/optimized/KryoSerialization2.java
  dubbo-serialization/dubbo-serialization-protobuf/src/main/java/org/apache/dubbo/common/serialize/protobuf/support/GenericProtobufSerialization.java
Labels: first-time-contributor, for/team-attention
