Repository apache/dubbo, pull requests merged in 2021-09, with the labels that each got.

#8783 Optimize some code of the dubbo metadata module
  dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/report/support/AbstractMetadataReport.java
  dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/report/support/Constants.java
Labels: type/code-quality

#8914 Add test case for ServiceInstanceMetadataUtilsTest
  dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/metadata/ServiceInstanceMetadataUtilsTest.java
Labels: type/unit-test

#8920 [3.0] add destroy() calling to close tomcat server port
  dubbo-remoting/dubbo-remoting-http/src/main/java/org/apache/dubbo/remoting/http/tomcat/TomcatHttpServer.java
  dubbo-remoting/dubbo-remoting-http/src/test/java/org/apache/dubbo/remoting/http/tomcat/TomcatHttpBinderTest.java
Labels: type/bug, version/3.x

#8921 [master] add destroy() calling to close tomcat server port
  dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java
  dubbo-remoting/dubbo-remoting-http/src/main/java/org/apache/dubbo/remoting/http/tomcat/TomcatHttpServer.java
  dubbo-remoting/dubbo-remoting-http/src/test/java/org/apache/dubbo/remoting/http/tomcat/TomcatHttpBinderTest.java
Labels: type/bug, version/2.7.x

#8619 fix: registry cast to AbstractRegistry error in telnet
  dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistry.java
Labels: type/bug
