Repository apache/dubbo, pull requests merged in 2021-03, with the labels that each got.

#6746 [Dubbo-6746]fix generic interface metadata publish log error
  dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/store/InMemoryWritableMetadataService.java
Labels: status/waiting-for-feedback

#6905 [ISSUE-#6904] Fix reflect invoke error in org.apache.dubbo.common.utils.PojoUtils#generalize
  dubbo-common/src/main/java/org/apache/dubbo/common/utils/PojoUtils.java
  dubbo-common/src/main/java/org/apache/dubbo/common/utils/ReflectUtils.java
  dubbo-common/src/test/java/org/apache/dubbo/common/PojoUtilsForNonPublicStaticTest.java
Labels: status/need-triage

#6909 [ISSUE-#6908] Extract AccessibleObject.setAccessible(boolean) to ReflectUtils
  dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/MergeableClusterInvoker.java
  dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/RoundRobinLoadBalanceTest.java
  dubbo-common/src/main/java/org/apache/dubbo/common/beanutil/JavaBeanSerializeUtil.java
  dubbo-common/src/main/java/org/apache/dubbo/common/json/J2oVisitor.java
  dubbo-common/src/main/java/org/apache/dubbo/common/utils/FieldUtils.java
  dubbo-common/src/main/java/org/apache/dubbo/common/utils/MethodUtils.java
  dubbo-common/src/main/java/org/apache/dubbo/common/utils/PojoUtils.java
  dubbo-common/src/main/java/org/apache/dubbo/common/utils/ReflectUtils.java
  dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ProviderModel.java
  dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ServiceDescriptor.java
  dubbo-common/src/test/java/org/apache/dubbo/common/bytecode/ClassGeneratorTest.java
  dubbo-common/src/test/java/org/apache/dubbo/common/config/EnvironmentConfigurationTest.java
  dubbo-common/src/test/java/org/apache/dubbo/common/utils/ReflectUtilsTest.java
  dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/AbstractConfigTest.java
  dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/status/SpringStatusChecker.java
  dubbo-configcenter/dubbo-configcenter-nacos/src/main/java/org/apache/dubbo/configcenter/support/nacos/NacosDynamicConfiguration.java
  dubbo-metadata/dubbo-metadata-report-failover/src/test/java/org/apache/dubbo/metadata/store/failover/FailoverMetadataReportTest.java
  dubbo-registry/dubbo-registry-default/src/test/java/org/apache/dubbo/registry/dubbo/RegistryDirectoryTest.java
  dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/handler/WrappedChannelHandlerTest.java
  dubbo-remoting/dubbo-remoting-etcd3/src/main/java/org/apache/dubbo/remoting/etcd/jetcd/JEtcdClientWrapper.java
  dubbo-remoting/dubbo-remoting-etcd3/src/test/java/org/apache/dubbo/remoting/etcd/jetcd/JEtcdClientTest.java
  dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AppResponse.java
  dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/GenericImplFilter.java
  dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/proxy/InvokerInvocationHandler.java
  dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/AccessLogFilterTest.java
  dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/filter/FutureFilter.java
  dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/DubboInvokerAvilableTest.java
  dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/ReferenceCountExchangeClientTest.java
  dubbo-rpc/dubbo-rpc-thrift/src/main/java/org/apache/dubbo/rpc/protocol/thrift/ThriftCodec.java
  dubbo-rpc/dubbo-rpc-thrift/src/test/java/org/apache/dubbo/rpc/protocol/thrift/ServiceMethodNotFoundTest.java
  dubbo-serialization/dubbo-serialization-kryo/src/main/java/org/apache/dubbo/common/serialize/kryo/CompatibleKryo.java
  dubbo-serialization/dubbo-serialization-kryo/src/main/java/org/apache/dubbo/common/serialize/kryo/utils/ReflectionUtils.java
  dubbo-serialization/dubbo-serialization-test/src/test/java/org/apache/dubbo/common/serialize/kryo/ReflectionUtilsTest.java
Labels: type/refactor

#6347 fix redundant code
  dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/Proxy.java
Labels: status/feedback-provided, type/refactor

#6848 fix OOM issue for Hessian2ObjectInput and Hessian2ObjectOutput
  dubbo-serialization/dubbo-serialization-hessian2/src/main/java/org/apache/dubbo/common/serialize/hessian2/Hessian2ObjectInput.java
  dubbo-serialization/dubbo-serialization-hessian2/src/main/java/org/apache/dubbo/common/serialize/hessian2/Hessian2ObjectOutput.java
Labels: type/bug

#5996 [Dubbo-Optimization]: polish DubboBootstrap
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java
Labels: status/waiting-for-feedback

#5994 [Dubbo-fix]: polish LFUCache
  dubbo-common/src/main/java/org/apache/dubbo/common/utils/LFUCache.java
  dubbo-common/src/test/java/org/apache/dubbo/common/utils/LFUCacheTest.java
Labels: status/waiting-for-feedback

#7374 cache Class avoid PermGen space OOM
  dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/Proxy.java
Labels: type/performance

#6500 Make keepalive parameters configurable on server
  dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
  dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyServer.java
Labels: status/waiting-for-feedback

#7370 [ISSUE-#7331] Ready common add check service is start success (#7331)
  dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/impl/Ready.java
Labels: type/enhancement

#6867 tackled some class<?> newInstance depeated, and some code refactor
  dubbo-common/src/main/java/org/apache/dubbo/common/beanutil/JavaBeanSerializeUtil.java
  dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/Mixin.java
  dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/Wrapper.java
  dubbo-common/src/main/java/org/apache/dubbo/common/compiler/support/ClassUtils.java
  dubbo-common/src/main/java/org/apache/dubbo/common/compiler/support/CtClassBuilder.java
  dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
  dubbo-common/src/main/java/org/apache/dubbo/common/utils/ReflectUtils.java
Labels: status/waiting-for-feedback

#7371 [ISSUE-#7363] Support a way to ignore check some key in parameters.
  dubbo-common/src/main/java/org/apache/dubbo/config/Constants.java
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ConfigValidationUtils.java
Labels: related/nacos

#7346 [ISSUE-#7129] NacosRegistry,NacosMetadataReport,NacosDynamicConfiguration compatible with innerclass symbol '$'
  dubbo-configcenter/dubbo-configcenter-nacos/src/main/java/org/apache/dubbo/configcenter/support/nacos/NacosConfigServiceWrapper.java
  dubbo-configcenter/dubbo-configcenter-nacos/src/main/java/org/apache/dubbo/configcenter/support/nacos/NacosDynamicConfiguration.java
  dubbo-metadata/dubbo-metadata-report-nacos/src/main/java/org/apache/dubbo/metadata/store/nacos/NacosConfigServiceWrapper.java
  dubbo-metadata/dubbo-metadata-report-nacos/src/main/java/org/apache/dubbo/metadata/store/nacos/NacosMetadataReport.java
  dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosNamingServiceWrapper.java
  dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java
  dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosServiceDiscovery.java
  dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/util/NacosNamingServiceUtils.java
Labels: related/nacos

#7443 Fix recover and zk notify concurrent problem.
  dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperRegistry.java
Labels: related/zookeeper

#6480 fix expire cache time
  dubbo-filter/dubbo-filter-cache/src/main/java/org/apache/dubbo/cache/support/expiring/ExpiringMap.java
Labels: status/waiting-for-feedback

#7126 [ISSUE-#7125] Promise doSubscribe notify and childListen notify synchronize.
  dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperRegistry.java
Labels: related/zookeeper

#6506 [optimization] polish RegistryProtocol in slight and fix up some word spelling
  dubbo-common/src/main/java/org/apache/dubbo/common/Parameters.java
  dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
  dubbo-common/src/main/java/org/apache/dubbo/common/utils/StringUtils.java
  dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/schema/DubboBeanDefinitionParser.java
  dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java
Labels: status/waiting-for-feedback, type/enhancement
