Repository apache/dubbo, pull requests merged in 2021-05, with the labels that each got.

#7494 solve the problem of repeatedly registering the BeanDefinition of the provider
  dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
  dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ApplicationModel.java
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java
  dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/AbstractInterfaceConfigTest.java
  dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ReferenceConfigTest.java
  dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ServiceConfigTest.java
  dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/event/listener/PublishingServiceDefinitionListenerTest.java
  dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/url/ExporterSideConfigUrlTest.java
  dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/url/InvokerSideConfigUrlTest.java
  dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceAnnotationBeanPostProcessorTest.java
  dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/annotation/ServiceAnnotationBeanPostProcessorTest.java
  dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/annotation/ServiceClassPostProcessorTest.java
  dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/config/MultipleServicesWithMethodConfigsTest.java
  dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/context/annotation/DubboComponentScanRegistrarTest.java
  dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/context/annotation/EnableDubboTest.java
  dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/schema/DubboNamespaceHandlerTest.java
  dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/schema/GenericServiceTest.java
  dubbo-config/dubbo-config-spring/src/test/resources/META-INF/spring/multiple-services-with-methods.xml
  dubbo-config/dubbo-config-spring/src/test/resources/org/apache/dubbo/config/spring/demo-provider-duplicate-service-bean.xml
  dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/report/MetadataReportInstance.java
  dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/report/support/AbstractMetadataReportFactory.java
  dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistryFactory.java
  dubbo-registry/dubbo-registry-default/src/test/java/org/apache/dubbo/registry/dubbo/RegistryStatusCheckerTest.java
Labels: related/spring

#7285 ZookeeperServiceDiscovery curator client support multi address.
  dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/util/CuratorFrameworkUtils.java
Labels: related/zookeeper

#7461 enhance LRUCache
  dubbo-common/src/main/java/org/apache/dubbo/common/utils/LRUCache.java
  dubbo-common/src/test/java/org/apache/dubbo/common/utils/LRUCacheTest.java
  dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/cache/CacheTest.java
  dubbo-filter/dubbo-filter-cache/src/test/java/org/apache/dubbo/cache/filter/CacheFilterTest.java
Labels: type/enhancement

#7825 Add tests for ZookeeperDynamicConfiguration
  dubbo-configcenter/dubbo-configcenter-zookeeper/src/test/java/org/apache/dubbo/configcenter/support/zookeeper/ZookeeperDynamicConfigurationTest.java
Labels: type/unit-test

#3855 Fix configuring priority judgment, with isAsync and isOneway (#3848)
  dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/support/RpcUtils.java
  dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/support/RpcUtilsTest.java
Labels: status/waiting-for-feedback

#7828 Update Pull Request Template
  PULL_REQUEST_TEMPLATE.md
Labels: status/READY-TO-MERGE

#7861 Add unit test for TraceTelnetHandler (#7843)
  dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/legacy/TraceTelnetHandlerTest.java
Labels: type/unit-test

#7860 Support url merge processor extension
  dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/Constants.java
  dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/UrlMergeProcessor.java
  dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/ClusterUtils.java
  dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/DefaultUrlMergeProcessor.java
  dubbo-cluster/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.rpc.cluster.UrlMergeProcessor
  dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/ClusterUtilsTest.java
  dubbo-common/src/main/java/org/apache/dubbo/config/ConsumerConfig.java
  dubbo-common/src/main/java/org/apache/dubbo/config/ProviderConfig.java
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/builders/ConsumerBuilder.java
  dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd
Labels: type/enhancement

#7440 fix multiple registry onEvent not triggered.
  dubbo-common/src/main/java/org/apache/dubbo/config/Constants.java
  dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
  dubbo-demo/dubbo-demo-xml/dubbo-demo-xml-consumer/pom.xml
  dubbo-demo/dubbo-demo-xml/dubbo-demo-xml-provider/pom.xml
  dubbo-demo/dubbo-demo-xml/dubbo-demo-xml-provider/src/main/resources/spring/dubbo-provider.xml
  dubbo-registry/dubbo-registry-multiple/src/main/java/org/apache/dubbo/registry/multiple/MultipleRegistryServiceDiscovery.java
  dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperServiceDiscovery.java
  dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperServiceDiscoveryChangeWatcher.java
Labels: type/bug
